#!/bin/bash
#SBATCH -A UKAEA-AP002-CPU
#SBATCH -p ukaea-spr-hbm
#SBATCH --nodes=7
#SBATCH --ntasks-per-node=112
#SBATCH -t 03:00:00
#SBATCH -J nek_off
#SBATCH --exclusive

PV_MPI_TASKS=196
PV_MPI_TASKS_PER_NODE=28

srun --ntasks=$PV_MPI_TASKS --ntasks-per-node=$PV_MPI_TASKS_PER_NODE bash -c \
'echo "Rank $SLURM_PROCID on $(hostname)"; \
 "/home/ir-eard1/rds/rds-ukaea-ap001/ir-eard1/paraview/ParaView-5.13.3-MPI-Linux-Python3.10-x86_64/bin/pvbatch" nek_off_refined_flat.py'
