#!/bin/bash
#SBATCH -A UKAEA-AP002-CPU
#SBATCH -p ukaea-spr-hbm-flat
#SBATCH --nodes=14
#SBATCH --ntasks-per-node=112
#SBATCH -t 03:00:00
#SBATCH -J pv_frontier_off_refined_numactl
#SBATCH --exclusive
##SBATCH --mem=1T

module load lua

PV_MPI_TASKS=392
PV_MPI_TASKS_PER_NODE=28

PARAVIEW_PATH="/home/ir-eard1/rds/rds-ukaea-ap001/ir-eard1/paraview/ParaView-5.13.3-MPI-Linux-Python3.10-x86_64"

srun --ntasks=$PV_MPI_TASKS --ntasks-per-node=$PV_MPI_TASKS_PER_NODE bash -c \
'echo "Rank $SLURM_PROCID on $(hostname)"; \
 numactl --preferred-many=8-15 ${PARAVIEW_PATH}"/bin/pvbatch" pv_paraview_nek_off_refined_numactl.py'
