#!/bin/bash
#SBATCH -A do015
#SBATCH -p dine2
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=16
#SBATCH -t 03:00:00
#SBATCH -J nek_off
#SBATCH --exclusive

module load intel_comp/2025.0.1
module load compiler-rt tbb umf compiler mpi
module list

PARAVIEW_PATH="../../ParaView-5.13.3-MPI-Linux-Python3.10-x86_64/"

mpiexec -np $SLURM_NTASKS -print-rank-map $PARAVIEW_PATH"/bin/pvbatch" test.py
